language: node_js
node_js:
- 12
script:
- npm run lint
- npm test
deploy:
  provider: heroku
  app: github-repo-abdo158
  api_key:
    secure: HTftIb1ak2PC+FnWrnxSzEqS2j2+jhF62HzUZx4HB4FlqqckfNKkH6A2mEci7mVqZuPzy8Q9gioAbtLWyw1WFr/mZVwDcr67xyc0uu947IRskeCHqXJyyXkoB5CcufVfg4WKS+WRpU4bd7iql53stksVdz+nC8U5HtDGrJwSn6CBh/d6Muw0ZBSu5tY/3YgDAWV1UfPURfJYdNG25m/5gvit9x2yMhgoBawLkpBcjR7/+f7Lq6cz8DTGv5fcP4OMxyOW4Gobkpu/z5hk434xp3nJAw/fXycfVjMaQ5Px/uG5Gx5i4ViyAKgQRVZKiGrev5Eeupa2sJ6+usg7Jj4jM8zzszctSHkoAA/zHrjF8mnBrXCcMB2dBMkKAEaJrgLjFkQF6iRmg36hKeg/HYs4z7ZAFQ7pv5/9fOQu05xCyo6h0pg1ErP6JOfAbjxE/joIxcQRbzrZl7YjuCPPeCTjxDQwRCTZsQfLsdVXjGxcsqxYq9BEf7xT766KruUUdRe9FX96570Z43du3TFb/RlYKqaOCOtEJGKAUsJwGG8XTevDdVcGwW8b8yik0O6/EZFZWxlHBcgUC2/Fy3guFxPzNIzzc7aN9ZdsooYS9QuYpkj+x8uvHs+xjk6iUmZcoWkQ4dSZyxBrYarzvFXt8eOV/47RHS7Ck3KczIoQfKjY69g=
