language: node_js
node_js:
- 12
script:
- npm run lint
- npm test
deploy:
  provider: heroku
  app: github-repo-abdo158
  api_key:
    secure: "JDQmk3FE3cZxpcb1gDuIdKCvyf3/GfhHp4tFTGspuUvBYCJI/PtUHBszdXoADbKyE1sOGeK7GI3FGw8PA5Qc2OfarDr6xGpQW7nh4+7ZunFdb/f4urcbBtzkgi1JvcBYW5wlI1m0PjUkvSQiqVkWq958oBL3qNlZPdWiPTzI/y8KDTnk1cMeBWLgz0nxS6AfsOgjB3KbAWn1bRMXlwi1XAM7qDg5Q5aUV1vg8eZokYGcItOls2LtgOLsiD6D8ABqUbbJhffO88+K8uijFKjsQ4lEmZnPbPo3TS8r6aTh6ihnoCzrOAUgCTcpeqGHcONEVpTPxLxH8boyxWihe/ekUIE+G823sZIb1x7jHaYOAz9L4RZhhTLfH/ycniD3oAFBroq8Sas6rFPxjhT+ojX4GdkgYw6GJw98JOYdoE20FWWyIpHmGboXYsgGaBVcA3GkMX0WTtCmON3Slp9HTBM6pDKbkIO3WQ/bRW9a76/5KInp3Kt8dHsD218beeRZGaZ/aWI/M7meg+wWjZSSexEPjmvJ3bJPd/L/8xmF8ieI3+hBisGw/8cHPth1ehUZRKyY2qUZmhFJrAU6J4mPOn/C8fp8Lb/e3jfv2NHwPTp7jqSOXVcyipoSKFB1/cHTxoMACl4QEJimk5eyDYB51Zu5rBqk9+fnH6CuyFueWv85oaE="
