language: node_js
node_js:
- 12
script:
- npm run lint
- npm test
deploy:
  provider: heroku
  app: github-repo-abdo158
  api_key:
    secure: Q5UHKdUZlTafxon8+m+aJdA1FNkcSqlDMWAynGy0nxS+SFg75xRutHv0FvIrF0hXKkSSX6LxjftoK0M21RQFKxQcq+n0NjBp0Ny1urWU8NljM9jkcd4r/Pn/sIsbqgAktQ1puKOKd81IBIgeU0huseomjUL3/XyqKy/g9JDJdGLYm5HHzDQUOBVkfjjm8ZRHyEZAQVbAIeuW9o77eOiqeSTmbDd2eNHnuRqLdgI9nUqa8tTE12MuO9fKdqaFg8VXi41u30vINfpH1Cvs2gOk0ZBPi2BL1ToknHQ6xZgmyGWxVxt3O2A4Yl5IYPVwnaSsOaAJDfdTrBMNUyBa1I/9CkF1WLmy079WNIWV1qrdtLe/uPlYqVF5WSDwq/NFs9nij656nTshAlDciYSIbXoCmxkEM4ygXq5gozhhU/TDGQPCSAVcr4kboUzX8RFAaa62MjEtazCIPMUdrmsQW2mjC+TbJfh98913VDw7p4XbLpVsIUCvTCrnWgNBctX1pGpnkt18/mGbmT2ZPfjU7SVoYkfLNwq43/SP+Os/CcTu0x3r1s/VnZ5VMrtvg0XcQN6ZuRUQ8YARqxgwLuPXKJyr3AfpRWUuhba2Q/LooV3qqghCkez7tKy/0DZG/oe3f9gshGhZdZjN50w5X3YLWHLQuKfeWZenI1+FXsJzQZegKRc=
